/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Greet: typeof import('./src/components/Greet.vue')['default']
    LeftTree: typeof import('./src/components/LeftTree/LeftTree.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NSpace: typeof import('naive-ui')['NSpace']
    NTree: typeof import('naive-ui')['NTree']
    SelectBaseDir: typeof import('./src/components/SelectBaseDir/SelectBaseDir.vue')['default']
  }
}
