name: Build and Upload Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.16.0

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies with pnpm
      run: pnpm install

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: x86_64-pc-windows-msvc

    - name: Build Tauri app
      run: pnpm tauri build

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: jx3-keyborad-exe
        path: src-tauri/target/release/jx3-keyborad.exe
