name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        rust-version: [stable]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.16.0

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Set up pnpm global bin
      run: |
        pnpm setup
        echo "PNPM_HOME=$(pnpm config get global-bin-dir)" >> $GITHUB_ENV
        echo "$(pnpm config get global-bin-dir)" >> $GITHUB_PATH

    - name: Install dependencies with pnpm
      run: pnpm install

    - name: Set up Rust ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        override: true
        target: x86_64-pc-windows-msvc

    - name: Install Tauri CLI
      run: pnpm add -g @tauri-apps/cli

    - name: Build Tauri app
      run: pnpm tauri build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tauri-app
        path: src-tauri/target/release/bundle/msi/*.msi
